"Tab"
set tabstop=4
set shiftwidth=4
set softtabstop=4

"Smart
set autoindent
set smartindent
set smarttab

set tw=80
syntax on

set number
set ruler

inoremap{      {}<Left>
inoremap{<CR>  {<CR>}<Esc>O
inoremap{{     {
inoremap{}     {}

colorscheme molokai