#!/bin/bash
#Kocsen Chung

#color
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='colordiff' #requires colordiff package

#personal shortcuts
alias sshnit='ssh kxc4519@nitron.rit.edu'
alias sshrpi='ssh sagehyuga@kocsenrpi.student.rit.edu'
alias x='startx'
alias inst="sudo yaourt -S "
alias batt="acpi -i"
alias wbatt="watch acpi -i"
alias connectwifi="sudo wifi-menu wlp9s0"
alias update="sudo yaourt -Syu"

#ls aliases
alias la='ls -a --color=auto'
alias ll="ls -al"
alias l="ls"
