#!/bin/bash
#Kocsen Chung

export PATH=/usr/local/bin:$PATH

#color
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='colordiff' #requires colordiff package

#personal shortcuts
alias install="sudo brew install "
#alias plz='sudo $(history -p !!)'

#SSH
alias sshnit='ssh kxc4519@nitron.se.rit.edu'
alias sshzbox='ssh potato@zbox.student.rit.edu'
alias sshzbox2='ssh kocsenc@zbox2.student.rit.edu'
alias sshvps='ssh potato@104.236.241.219'
alias sshrate='ssh -p 2222 kocsenc@ratemycoop.io'
alias sshandroid='ssh kxc4519@vm-017.main.ad.rit.edu'
alias git lola='git log --graph --decorate --pretty=oneline --abbrev-commit --all'

#ls aliases
alias la='ls -a --color=auto'
alias ll="ls -al"
alias l="ls"
